
#h2
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  api-docs:
    path: /employee-api
